Repository Trust-Machines/stacks-sbtc, pull requests merged in 2023-05, with the labels that each got.

#290 [Clarity] Clarity unit tests for sBTC Mini token contract
  .github/workflows/clarinet.yml
  bin/install_clarinet_action.sh
  bin/install_clarinet_ubuntu.sh
  sbtc-mini/Clarinet.toml
  sbtc-mini/README.md
  sbtc-mini/contracts/sbtc-testnet-debug-controller.clar
  sbtc-mini/ext/generate-tests.ts
  sbtc-mini/scripts/coverage-report.sh
  sbtc-mini/scripts/test.sh
  sbtc-mini/tests/sbtc-controller_test.clar
  sbtc-mini/tests/sbtc-token_test.clar
Labels: sbtc-mini, testing

#321 Add algo Bug and Feature Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/risk-issue.md
Labels: enhancement

#391 fix: Correct serialization of bitcoin wallet public key
  stacks-coordinator/src/stacks_wallet.rs
Labels: bug, blockchain-workstream

#393 fix: Only use env filter to filter tracing logs
  frost-coordinator/src/main.rs
  frost-signer/src/logging.rs
  frost-signer/src/main.rs
  stacks-coordinator/src/main.rs
  stacks-signer/src/main.rs
Labels: bug, blockchain-workstream
