Repository Trust-Machines/stacks-sbtc, pull requests merged in 2023-06, with the labels that each got.

#382 Reveal test vectors for PegIn and PegOutRequest
  test-vectors/Cargo.toml
  test-vectors/src/main.rs
  test-vectors/src/peg_in.rs
  test-vectors/src/peg_out.rs
Labels: chore, blockchain-workstream

#348 docs: Allow variable-sized data payloads in commit-reveal
  sbtc-planning/commit-reveal-ops.md
Labels: documentation, blockchain-workstream

#304 Clarity/clarity bitcoin segwit
  sbtc-mini/Clarinet.toml
  sbtc-mini/contracts/clarity-bitcoin.clar
  sbtc-mini/contracts/sbtc-peg-in-processor.clar
  sbtc-mini/contracts/sbtc-peg-out-processor.clar
  sbtc-mini/tests/clarity-bitcoin_test.clar
Labels: clarity-workstream

#405 Load the wallet address using importdescriptors
  frost-test/tests/frost-btc.rs
  misc/bitcoin_rpc_scripts/createwallet.sh
  misc/bitcoin_rpc_scripts/getdescriptorinfo.sh
  misc/bitcoin_rpc_scripts/importaddress.sh
  misc/bitcoin_rpc_scripts/listunspent.sh
  misc/bitcoin_rpc_scripts/listwallets.sh
  misc/bitcoin_rpc_scripts/unloadwallet.sh
  stacks-coordinator/Cargo.toml
  stacks-coordinator/src/bitcoin_node.rs
  stacks-coordinator/src/bitcoin_wallet.rs
  stacks-coordinator/src/coordinator.rs
  stacks-coordinator/src/peg_wallet.rs
  stacks-coordinator/tests/local_bitcoin_node.rs
  test-utils/Cargo.toml
  test-utils/src/lib.rs
Labels: bug, blockchain-workstream, sbtc-alpha

#461 refactor: Rename sbtc-op to sbtc-cli #460
  Cargo.toml
  sbtc-cli/Cargo.toml
  sbtc-cli/README.md
  sbtc-cli/src/main.rs
Labels: chore, blockchain-workstream

#452 Add logging to improve coordinator debugging
  stacks-coordinator/src/coordinator.rs
  stacks-coordinator/src/peg_queue/sqlite_peg_queue.rs
Labels: enhancement, sbtc-alpha

#345 Add initial sbtc stacks coordinator README.md
  stacks-coordinator-mini/README.md
Labels: stacks-coordinator

#347 Include clariform spread formatting
  sbtc-mini/scripts/coverage-report.sh
  sbtc-mini/scripts/test.sh
Labels: clarity-workstream

#377 sBTC Mini Stacking Pool & Peg-Transfer 1st Drafts
  .DS_Store
  sbtc-mini/.gitignore
  sbtc-mini/Clarinet.toml
  sbtc-mini/README.md
  sbtc-mini/contracts/clarity-bitcoin.clar
  sbtc-mini/contracts/pox-3.clar
  sbtc-mini/contracts/sbtc-btc-tx-helper.clar
  sbtc-mini/contracts/sbtc-controller.clar
  sbtc-mini/contracts/sbtc-peg-in-processor.clar
  sbtc-mini/contracts/sbtc-peg-transfer.clar
  sbtc-mini/contracts/sbtc-registry.clar
  sbtc-mini/contracts/sbtc-stacking-pool.clar
  sbtc-mini/ext/generate-tests.ts
  sbtc-mini/tests/clarity-bitcoin_test.clar
  sbtc-mini/tests/sbtc-peg-in-processor_test.clar
  sbtc-mini/tests/sbtc-registry_test.clar
  sbtc-mini/tests/sbtc-stacking-pool_test.clar
Labels: clarity-workstream

#319 First version of sBTC Mini peg-in and registry
  .DS_Store
  sbtc-mini/.gitignore
  sbtc-mini/Clarinet.toml
  sbtc-mini/contracts/sbtc-btc-tx-helper.clar
  sbtc-mini/contracts/sbtc-controller.clar
  sbtc-mini/contracts/sbtc-peg-in-processor.clar
  sbtc-mini/contracts/sbtc-registry.clar
  sbtc-mini/contracts/sbtc-testnet-debug-controller.clar
  sbtc-mini/scripts/test.sh
  sbtc-mini/tests/sbtc-btc-tx-helper_test.clar
  sbtc-mini/tests/sbtc-peg-in-processor_test.clar
Labels: sbtc-mini
